/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.congdan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the CSMSCongDan service. Represents a row in the &quot;csmscongdan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.congdan.model.impl.CSMSCongDanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.congdan.model.impl.CSMSCongDanImpl}.
 * </p>
 *
 * @author ADMIN
 * @see CSMSCongDan
 * @see com.congdan.model.impl.CSMSCongDanImpl
 * @see com.congdan.model.impl.CSMSCongDanModelImpl
 * @generated
 */
public interface CSMSCongDanModel extends BaseModel<CSMSCongDan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c s m s cong dan model instance should use the {@link CSMSCongDan} interface instead.
	 */

	/**
	 * Returns the primary key of this c s m s cong dan.
	 *
	 * @return the primary key of this c s m s cong dan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this c s m s cong dan.
	 *
	 * @param primaryKey the primary key of this c s m s cong dan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the idcsms cong dan of this c s m s cong dan.
	 *
	 * @return the idcsms cong dan of this c s m s cong dan
	 */
	public long getIdcsmsCongDan();

	/**
	 * Sets the idcsms cong dan of this c s m s cong dan.
	 *
	 * @param IdcsmsCongDan the idcsms cong dan of this c s m s cong dan
	 */
	public void setIdcsmsCongDan(long IdcsmsCongDan);

	/**
	 * Returns the ho of this c s m s cong dan.
	 *
	 * @return the ho of this c s m s cong dan
	 */
	@AutoEscape
	public String getHo();

	/**
	 * Sets the ho of this c s m s cong dan.
	 *
	 * @param Ho the ho of this c s m s cong dan
	 */
	public void setHo(String Ho);

	/**
	 * Returns the dem of this c s m s cong dan.
	 *
	 * @return the dem of this c s m s cong dan
	 */
	@AutoEscape
	public String getDem();

	/**
	 * Sets the dem of this c s m s cong dan.
	 *
	 * @param Dem the dem of this c s m s cong dan
	 */
	public void setDem(String Dem);

	/**
	 * Returns the ten of this c s m s cong dan.
	 *
	 * @return the ten of this c s m s cong dan
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this c s m s cong dan.
	 *
	 * @param Ten the ten of this c s m s cong dan
	 */
	public void setTen(String Ten);

	/**
	 * Returns the ngay sinh of this c s m s cong dan.
	 *
	 * @return the ngay sinh of this c s m s cong dan
	 */
	public Date getNgaySinh();

	/**
	 * Sets the ngay sinh of this c s m s cong dan.
	 *
	 * @param NgaySinh the ngay sinh of this c s m s cong dan
	 */
	public void setNgaySinh(Date NgaySinh);

	/**
	 * Returns the gioi tinh ID of this c s m s cong dan.
	 *
	 * @return the gioi tinh ID of this c s m s cong dan
	 */
	public long getGioiTinhId();

	/**
	 * Sets the gioi tinh ID of this c s m s cong dan.
	 *
	 * @param GioiTinhId the gioi tinh ID of this c s m s cong dan
	 */
	public void setGioiTinhId(long GioiTinhId);

	/**
	 * Returns the noi sinh chi tiet of this c s m s cong dan.
	 *
	 * @return the noi sinh chi tiet of this c s m s cong dan
	 */
	@AutoEscape
	public String getNoiSinhChiTiet();

	/**
	 * Sets the noi sinh chi tiet of this c s m s cong dan.
	 *
	 * @param NoiSinhChiTiet the noi sinh chi tiet of this c s m s cong dan
	 */
	public void setNoiSinhChiTiet(String NoiSinhChiTiet);

	/**
	 * Returns the noi sinh xa ID of this c s m s cong dan.
	 *
	 * @return the noi sinh xa ID of this c s m s cong dan
	 */
	public long getNoiSinhXaId();

	/**
	 * Sets the noi sinh xa ID of this c s m s cong dan.
	 *
	 * @param NoiSinhXaId the noi sinh xa ID of this c s m s cong dan
	 */
	public void setNoiSinhXaId(long NoiSinhXaId);

	/**
	 * Returns the noi sinh huyen ID of this c s m s cong dan.
	 *
	 * @return the noi sinh huyen ID of this c s m s cong dan
	 */
	public long getNoiSinhHuyenId();

	/**
	 * Sets the noi sinh huyen ID of this c s m s cong dan.
	 *
	 * @param NoiSinhHuyenId the noi sinh huyen ID of this c s m s cong dan
	 */
	public void setNoiSinhHuyenId(long NoiSinhHuyenId);

	/**
	 * Returns the noi sinh tinh ID of this c s m s cong dan.
	 *
	 * @return the noi sinh tinh ID of this c s m s cong dan
	 */
	public long getNoiSinhTinhId();

	/**
	 * Sets the noi sinh tinh ID of this c s m s cong dan.
	 *
	 * @param NoiSinhTinhId the noi sinh tinh ID of this c s m s cong dan
	 */
	public void setNoiSinhTinhId(long NoiSinhTinhId);

	/**
	 * Returns the dan toc ID of this c s m s cong dan.
	 *
	 * @return the dan toc ID of this c s m s cong dan
	 */
	@AutoEscape
	public String getDanTocId();

	/**
	 * Sets the dan toc ID of this c s m s cong dan.
	 *
	 * @param DanTocId the dan toc ID of this c s m s cong dan
	 */
	public void setDanTocId(String DanTocId);

	/**
	 * Returns the quoc tich ID of this c s m s cong dan.
	 *
	 * @return the quoc tich ID of this c s m s cong dan
	 */
	@AutoEscape
	public String getQuocTichId();

	/**
	 * Sets the quoc tich ID of this c s m s cong dan.
	 *
	 * @param QuocTichId the quoc tich ID of this c s m s cong dan
	 */
	public void setQuocTichId(String QuocTichId);

	/**
	 * Returns the ton giao ID of this c s m s cong dan.
	 *
	 * @return the ton giao ID of this c s m s cong dan
	 */
	@AutoEscape
	public String getTonGiaoId();

	/**
	 * Sets the ton giao ID of this c s m s cong dan.
	 *
	 * @param TonGiaoId the ton giao ID of this c s m s cong dan
	 */
	public void setTonGiaoId(String TonGiaoId);

	/**
	 * Returns the dia chi thuong tru of this c s m s cong dan.
	 *
	 * @return the dia chi thuong tru of this c s m s cong dan
	 */
	@AutoEscape
	public String getDiaChiThuongTru();

	/**
	 * Sets the dia chi thuong tru of this c s m s cong dan.
	 *
	 * @param DiaChiThuongTru the dia chi thuong tru of this c s m s cong dan
	 */
	public void setDiaChiThuongTru(String DiaChiThuongTru);

	/**
	 * Returns the dia chi thuong tru xa ID of this c s m s cong dan.
	 *
	 * @return the dia chi thuong tru xa ID of this c s m s cong dan
	 */
	public long getDiaChiThuongTruXaId();

	/**
	 * Sets the dia chi thuong tru xa ID of this c s m s cong dan.
	 *
	 * @param DiaChiThuongTruXaId the dia chi thuong tru xa ID of this c s m s cong dan
	 */
	public void setDiaChiThuongTruXaId(long DiaChiThuongTruXaId);

	/**
	 * Returns the dia chi thuong tru huyen ID of this c s m s cong dan.
	 *
	 * @return the dia chi thuong tru huyen ID of this c s m s cong dan
	 */
	public long getDiaChiThuongTruHuyenId();

	/**
	 * Sets the dia chi thuong tru huyen ID of this c s m s cong dan.
	 *
	 * @param DiaChiThuongTruHuyenId the dia chi thuong tru huyen ID of this c s m s cong dan
	 */
	public void setDiaChiThuongTruHuyenId(long DiaChiThuongTruHuyenId);

	/**
	 * Returns the dia chi thuong tru tinh ID of this c s m s cong dan.
	 *
	 * @return the dia chi thuong tru tinh ID of this c s m s cong dan
	 */
	public long getDiaChiThuongTruTinhId();

	/**
	 * Sets the dia chi thuong tru tinh ID of this c s m s cong dan.
	 *
	 * @param DiaChiThuongTruTinhId the dia chi thuong tru tinh ID of this c s m s cong dan
	 */
	public void setDiaChiThuongTruTinhId(long DiaChiThuongTruTinhId);

	/**
	 * Returns the dia chi hien nay of this c s m s cong dan.
	 *
	 * @return the dia chi hien nay of this c s m s cong dan
	 */
	@AutoEscape
	public String getDiaChiHienNay();

	/**
	 * Sets the dia chi hien nay of this c s m s cong dan.
	 *
	 * @param DiaChiHienNay the dia chi hien nay of this c s m s cong dan
	 */
	public void setDiaChiHienNay(String DiaChiHienNay);

	/**
	 * Returns the dia chi hien nay xa ID of this c s m s cong dan.
	 *
	 * @return the dia chi hien nay xa ID of this c s m s cong dan
	 */
	public long getDiaChiHienNayXaId();

	/**
	 * Sets the dia chi hien nay xa ID of this c s m s cong dan.
	 *
	 * @param DiaChiHienNayXaId the dia chi hien nay xa ID of this c s m s cong dan
	 */
	public void setDiaChiHienNayXaId(long DiaChiHienNayXaId);

	/**
	 * Returns the dia chi hien nay huyen ID of this c s m s cong dan.
	 *
	 * @return the dia chi hien nay huyen ID of this c s m s cong dan
	 */
	public long getDiaChiHienNayHuyenId();

	/**
	 * Sets the dia chi hien nay huyen ID of this c s m s cong dan.
	 *
	 * @param DiaChiHienNayHuyenId the dia chi hien nay huyen ID of this c s m s cong dan
	 */
	public void setDiaChiHienNayHuyenId(long DiaChiHienNayHuyenId);

	/**
	 * Returns the dia chi hien nay tinh ID of this c s m s cong dan.
	 *
	 * @return the dia chi hien nay tinh ID of this c s m s cong dan
	 */
	public long getDiaChiHienNayTinhId();

	/**
	 * Sets the dia chi hien nay tinh ID of this c s m s cong dan.
	 *
	 * @param DiaChiHienNayTinhId the dia chi hien nay tinh ID of this c s m s cong dan
	 */
	public void setDiaChiHienNayTinhId(long DiaChiHienNayTinhId);

	/**
	 * Returns the tinh trang of this c s m s cong dan.
	 *
	 * @return the tinh trang of this c s m s cong dan
	 */
	public long getTinhTrang();

	/**
	 * Sets the tinh trang of this c s m s cong dan.
	 *
	 * @param TinhTrang the tinh trang of this c s m s cong dan
	 */
	public void setTinhTrang(long TinhTrang);

	/**
	 * Returns the tinht tranghon nhan ID of this c s m s cong dan.
	 *
	 * @return the tinht tranghon nhan ID of this c s m s cong dan
	 */
	public long getTinhtTranghonNhanId();

	/**
	 * Sets the tinht tranghon nhan ID of this c s m s cong dan.
	 *
	 * @param TinhtTranghonNhanId the tinht tranghon nhan ID of this c s m s cong dan
	 */
	public void setTinhtTranghonNhanId(long TinhtTranghonNhanId);

	/**
	 * Returns the socmnd of this c s m s cong dan.
	 *
	 * @return the socmnd of this c s m s cong dan
	 */
	@AutoEscape
	public String getSocmnd();

	/**
	 * Sets the socmnd of this c s m s cong dan.
	 *
	 * @param socmnd the socmnd of this c s m s cong dan
	 */
	public void setSocmnd(String socmnd);

	/**
	 * Returns the ngay cap c m n d of this c s m s cong dan.
	 *
	 * @return the ngay cap c m n d of this c s m s cong dan
	 */
	public Date getNgayCapCMND();

	/**
	 * Sets the ngay cap c m n d of this c s m s cong dan.
	 *
	 * @param NgayCapCMND the ngay cap c m n d of this c s m s cong dan
	 */
	public void setNgayCapCMND(Date NgayCapCMND);

	/**
	 * Returns the noi cap c m n d of this c s m s cong dan.
	 *
	 * @return the noi cap c m n d of this c s m s cong dan
	 */
	@AutoEscape
	public String getNoiCapCMND();

	/**
	 * Sets the noi cap c m n d of this c s m s cong dan.
	 *
	 * @param NoiCapCMND the noi cap c m n d of this c s m s cong dan
	 */
	public void setNoiCapCMND(String NoiCapCMND);

	/**
	 * Returns the so ho khau of this c s m s cong dan.
	 *
	 * @return the so ho khau of this c s m s cong dan
	 */
	@AutoEscape
	public String getSoHoKhau();

	/**
	 * Sets the so ho khau of this c s m s cong dan.
	 *
	 * @param SoHoKhau the so ho khau of this c s m s cong dan
	 */
	public void setSoHoKhau(String SoHoKhau);

	/**
	 * Returns the la chu ho of this c s m s cong dan.
	 *
	 * @return the la chu ho of this c s m s cong dan
	 */
	public long getLaChuHo();

	/**
	 * Sets the la chu ho of this c s m s cong dan.
	 *
	 * @param LaChuHo the la chu ho of this c s m s cong dan
	 */
	public void setLaChuHo(long LaChuHo);

	/**
	 * Returns the quan he chu ho ID of this c s m s cong dan.
	 *
	 * @return the quan he chu ho ID of this c s m s cong dan
	 */
	public long getQuanHeChuHoId();

	/**
	 * Sets the quan he chu ho ID of this c s m s cong dan.
	 *
	 * @param QuanHeChuHoId the quan he chu ho ID of this c s m s cong dan
	 */
	public void setQuanHeChuHoId(long QuanHeChuHoId);

	/**
	 * Returns the so ho chieu of this c s m s cong dan.
	 *
	 * @return the so ho chieu of this c s m s cong dan
	 */
	@AutoEscape
	public String getSoHoChieu();

	/**
	 * Sets the so ho chieu of this c s m s cong dan.
	 *
	 * @param SoHoChieu the so ho chieu of this c s m s cong dan
	 */
	public void setSoHoChieu(String SoHoChieu);

	/**
	 * Returns the ngay cap s h c of this c s m s cong dan.
	 *
	 * @return the ngay cap s h c of this c s m s cong dan
	 */
	public Date getNgayCapSHC();

	/**
	 * Sets the ngay cap s h c of this c s m s cong dan.
	 *
	 * @param NgayCapSHC the ngay cap s h c of this c s m s cong dan
	 */
	public void setNgayCapSHC(Date NgayCapSHC);

	/**
	 * Returns the ngay het han s h c of this c s m s cong dan.
	 *
	 * @return the ngay het han s h c of this c s m s cong dan
	 */
	public Date getNgayHetHanSHC();

	/**
	 * Sets the ngay het han s h c of this c s m s cong dan.
	 *
	 * @param NgayHetHanSHC the ngay het han s h c of this c s m s cong dan
	 */
	public void setNgayHetHanSHC(Date NgayHetHanSHC);

	/**
	 * Returns the noi cap s h c of this c s m s cong dan.
	 *
	 * @return the noi cap s h c of this c s m s cong dan
	 */
	@AutoEscape
	public String getNoiCapSHC();

	/**
	 * Sets the noi cap s h c of this c s m s cong dan.
	 *
	 * @param NoiCapSHC the noi cap s h c of this c s m s cong dan
	 */
	public void setNoiCapSHC(String NoiCapSHC);

	/**
	 * Returns the ma cong dan of this c s m s cong dan.
	 *
	 * @return the ma cong dan of this c s m s cong dan
	 */
	public long getMaCongDan();

	/**
	 * Sets the ma cong dan of this c s m s cong dan.
	 *
	 * @param MaCongDan the ma cong dan of this c s m s cong dan
	 */
	public void setMaCongDan(long MaCongDan);

	/**
	 * Returns the image data of this c s m s cong dan.
	 *
	 * @return the image data of this c s m s cong dan
	 */
	public Blob getImageData();

	/**
	 * Sets the image data of this c s m s cong dan.
	 *
	 * @param ImageData the image data of this c s m s cong dan
	 */
	public void setImageData(Blob ImageData);

	/**
	 * Returns the img name of this c s m s cong dan.
	 *
	 * @return the img name of this c s m s cong dan
	 */
	@AutoEscape
	public String getImgName();

	/**
	 * Sets the img name of this c s m s cong dan.
	 *
	 * @param ImgName the img name of this c s m s cong dan
	 */
	public void setImgName(String ImgName);

	/**
	 * Returns the ten cha of this c s m s cong dan.
	 *
	 * @return the ten cha of this c s m s cong dan
	 */
	@AutoEscape
	public String getTenCha();

	/**
	 * Sets the ten cha of this c s m s cong dan.
	 *
	 * @param TenCha the ten cha of this c s m s cong dan
	 */
	public void setTenCha(String TenCha);

	/**
	 * Returns the ngay sinh cha of this c s m s cong dan.
	 *
	 * @return the ngay sinh cha of this c s m s cong dan
	 */
	public Date getNgaySinhCha();

	/**
	 * Sets the ngay sinh cha of this c s m s cong dan.
	 *
	 * @param NgaySinhCha the ngay sinh cha of this c s m s cong dan
	 */
	public void setNgaySinhCha(Date NgaySinhCha);

	/**
	 * Returns the ten me of this c s m s cong dan.
	 *
	 * @return the ten me of this c s m s cong dan
	 */
	@AutoEscape
	public String getTenMe();

	/**
	 * Sets the ten me of this c s m s cong dan.
	 *
	 * @param TenMe the ten me of this c s m s cong dan
	 */
	public void setTenMe(String TenMe);

	/**
	 * Returns the ngay sinh me of this c s m s cong dan.
	 *
	 * @return the ngay sinh me of this c s m s cong dan
	 */
	public Date getNgaySinhMe();

	/**
	 * Sets the ngay sinh me of this c s m s cong dan.
	 *
	 * @param NgaySinhMe the ngay sinh me of this c s m s cong dan
	 */
	public void setNgaySinhMe(Date NgaySinhMe);

	/**
	 * Returns the ten vo of this c s m s cong dan.
	 *
	 * @return the ten vo of this c s m s cong dan
	 */
	@AutoEscape
	public String getTenVo();

	/**
	 * Sets the ten vo of this c s m s cong dan.
	 *
	 * @param TenVo the ten vo of this c s m s cong dan
	 */
	public void setTenVo(String TenVo);

	/**
	 * Returns the ngay sinh vo of this c s m s cong dan.
	 *
	 * @return the ngay sinh vo of this c s m s cong dan
	 */
	public Date getNgaySinhVo();

	/**
	 * Sets the ngay sinh vo of this c s m s cong dan.
	 *
	 * @param NgaySinhVo the ngay sinh vo of this c s m s cong dan
	 */
	public void setNgaySinhVo(Date NgaySinhVo);

	/**
	 * Returns the sdt of this c s m s cong dan.
	 *
	 * @return the sdt of this c s m s cong dan
	 */
	public long getSdt();

	/**
	 * Sets the sdt of this c s m s cong dan.
	 *
	 * @param Sdt the sdt of this c s m s cong dan
	 */
	public void setSdt(long Sdt);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.congdan.model.CSMSCongDan csmsCongDan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.congdan.model.CSMSCongDan> toCacheModel();

	@Override
	public com.congdan.model.CSMSCongDan toEscapedModel();

	@Override
	public com.congdan.model.CSMSCongDan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}