/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.congdan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Huyen service. Represents a row in the &quot;huyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.congdan.model.impl.HuyenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.congdan.model.impl.HuyenImpl}.
 * </p>
 *
 * @author ADMIN
 * @see Huyen
 * @see com.congdan.model.impl.HuyenImpl
 * @see com.congdan.model.impl.HuyenModelImpl
 * @generated
 */
public interface HuyenModel extends BaseModel<Huyen> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a huyen model instance should use the {@link Huyen} interface instead.
	 */

	/**
	 * Returns the primary key of this huyen.
	 *
	 * @return the primary key of this huyen
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this huyen.
	 *
	 * @param primaryKey the primary key of this huyen
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this huyen.
	 *
	 * @return the ID of this huyen
	 */
	public long getId();

	/**
	 * Sets the ID of this huyen.
	 *
	 * @param Id the ID of this huyen
	 */
	public void setId(long Id);

	/**
	 * Returns the name of this huyen.
	 *
	 * @return the name of this huyen
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this huyen.
	 *
	 * @param Name the name of this huyen
	 */
	public void setName(String Name);

	/**
	 * Returns the type of this huyen.
	 *
	 * @return the type of this huyen
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this huyen.
	 *
	 * @param Type the type of this huyen
	 */
	public void setType(String Type);

	/**
	 * Returns the tinh ID of this huyen.
	 *
	 * @return the tinh ID of this huyen
	 */
	public long getTinhId();

	/**
	 * Sets the tinh ID of this huyen.
	 *
	 * @param TinhId the tinh ID of this huyen
	 */
	public void setTinhId(long TinhId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.congdan.model.Huyen huyen);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.congdan.model.Huyen> toCacheModel();

	@Override
	public com.congdan.model.Huyen toEscapedModel();

	@Override
	public com.congdan.model.Huyen toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}