/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.congdan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Xa service. Represents a row in the &quot;xa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.congdan.model.impl.XaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.congdan.model.impl.XaImpl}.
 * </p>
 *
 * @author ADMIN
 * @see Xa
 * @see com.congdan.model.impl.XaImpl
 * @see com.congdan.model.impl.XaModelImpl
 * @generated
 */
public interface XaModel extends BaseModel<Xa> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a xa model instance should use the {@link Xa} interface instead.
	 */

	/**
	 * Returns the primary key of this xa.
	 *
	 * @return the primary key of this xa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this xa.
	 *
	 * @param primaryKey the primary key of this xa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this xa.
	 *
	 * @return the ID of this xa
	 */
	public long getId();

	/**
	 * Sets the ID of this xa.
	 *
	 * @param Id the ID of this xa
	 */
	public void setId(long Id);

	/**
	 * Returns the name of this xa.
	 *
	 * @return the name of this xa
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this xa.
	 *
	 * @param Name the name of this xa
	 */
	public void setName(String Name);

	/**
	 * Returns the type of this xa.
	 *
	 * @return the type of this xa
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this xa.
	 *
	 * @param Type the type of this xa
	 */
	public void setType(String Type);

	/**
	 * Returns the huyen ID of this xa.
	 *
	 * @return the huyen ID of this xa
	 */
	public long getHuyenId();

	/**
	 * Sets the huyen ID of this xa.
	 *
	 * @param HuyenId the huyen ID of this xa
	 */
	public void setHuyenId(long HuyenId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.congdan.model.Xa xa);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.congdan.model.Xa> toCacheModel();

	@Override
	public com.congdan.model.Xa toEscapedModel();

	@Override
	public com.congdan.model.Xa toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}